name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: main
        run: |
          npm ci
          npm run lint
          npm run test:unit -- --coverage
          npm run build:lib
          npm run build:demo
          npm run codecov